apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
    - name: grpc-order
      protocol: TCP
      port: 50052
      targetPort: 50052

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
      version: v1
  template:
    metadata:
      labels:
        app: order
        version: v1
    spec:
      containers:
        - name: order
          image: cartify/order:0.1
          env:
            - name: DATABASE
              value: "mongodb://order-db:27017/orders"
            - name: RABBITMQ
              value: "amqp://guest:guest@rabbitmq:5672/"
          ports:
            - containerPort: 50052
          livenessProbe:
            grpc:
              port: 50052
            initialDelaySeconds: 10
          readinessProbe:
            grpc:
              port: 50052
            initialDelaySeconds: 10
